# STAGE 1: Build the binary
FROM mozilla/sbt AS builder

WORKDIR /src
COPY . .
RUN apt-get update && apt-get install -y nodejs npm sbt
RUN sbt -mem 2048 dist
RUN mkdir dist
RUN cd dist && unzip /src/app/jvm/target/universal/*.zip


# STAGE 2: Run the binary
FROM openjdk:11-jre

COPY --from=builder /src/dist/server-1.0 /app

WORKDIR /app
